- name: Deploy Application
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Deploy built application
      copy:
        src: ../src/ambilight.py
        dest: /home/luca/Ambilight/
        owner: luca
        group: luca
    - name: Deploy JSON
      copy:
        src: ../src/config.json
        dest: /home/luca/Ambilight/
        owner: luca
        group: luca
    - name: Deploy startAmbilight.sh
      copy:
        src: ../src/startAmbilight.sh
        dest: /home/luca/Ambilight/
        mode: '0777'
        owner: luca
        group: luca
    - name: Deploy stopAmbilight.sh
      copy:
        src: ../src/stopAmbilight.sh
        dest: /home/luca/Ambilight/
        mode: '0777'
        owner: luca
        group: luca